import './spec/utils.spec.js';
import './spec/config.spec.js';
import './spec/refererDetection.spec.js';
import './spec/tcfUtils.spec.js';
import './spec/consentProvider.spec.js';
import './spec/id5Instance.spec.js';
import './spec/id5InstanceLite.spec.js';
import './spec/api_counters.spec.js';
import './spec/api_async_responses.spec.js'
import './spec/api.spec.js';
import './spec/id5PrebidModule.spec.js';
import './spec/eventsTracker.spec.js'
