import './spec/utils.spec.js';
import './spec/config.spec.js';
import './spec/refererDetection.spec.js';
import './spec/tcfUtils.spec.js';
import './spec/consentProvider.spec.js';
import './spec/id5Instance.spec.js';
import './spec/api_counters.spec.js';
import './spec/api_id_refresh.spec.js';
import './spec/api.spec.js';
