stages:
  - build
  - release

variables:
  CACHE_FALLBACK_KEY: master

image: registry.gitlab.com/id5-sync/infrastructure/ci-image-node-google-chrome:18.4.0-102.0.5005.61-2

build:
  stage: build
  script:
    - npm install --global gulp-cli
    - npm ci
    - npm run build:all
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG

prepare_release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE !~ "/^Release v.*/"
      when: manual
  before_script:
    - git config user.email $GITLAB_USER_EMAIL
    - git config user.name $GITLAB_USER_LOGIN
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no \n\n" > ~/.ssh/config'
    - git checkout -B "$CI_COMMIT_REF_NAME"
    - git remote rm origin && git remote add origin "git@gitlab.com:id5-sync/id5-api.js.git"
  script:
    - npm run prepare_release
    - npm ci
    - npm run build:all
    - git push origin HEAD:$CI_COMMIT_REF_NAME --tags
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG

gitlab_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: manual
  script:
    - echo "Create release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: ./release_notes/$CI_COMMIT_TAG.md
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG

github_release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: manual
  script:
    - bash release-github.sh $CI_COMMIT_TAG
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG

npm_release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: manual
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - bash release-npm.sh
  cache:
    paths:
      - "$CI_PROJECT_DIR/node_modules"
    key: $CI_COMMIT_REF_SLUG
